# Deploy the vite + react + typescript project to GitHub Pages
# This workflow builds the project and deploys it to GitHub Pages
name: Deploy to GitHub Pages
# This workflow is triggered by the completion of the static code analysis pipeline
on:
  workflow_run:
    workflows: ["static_code_analysis_pipeline"]
    types:
      - completed
permissions:
  contents: read        # Needed to check out code
  pages: write          # Needed to deploy to GitHub Pages
  id-token: write       # Optional: useful if you use OIDC tokens (can be removed if unused)

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # static code analysis is done in the static_code_analysis_pipeline
  # this job will only run if the static code analysis pipeline is successful
  # and the branch is Prod
  # it will build the project and deploy it to GitHub Pages
  build-and-deploy:
    name: Build & Deploy the project
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'Prod' }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x # Specify the Node.js version
          cache: 'npm'

      - name: Install dependencies
        run: npm ci # Use npm ci for faster installs

      - name: Build the project
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload build output as Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
