name: GitHub Pages Deployment Workflow

on:
  workflow_run:
    workflows: [SAST and CI Pipeline for Portfolio]
    types:
      - completed
    branches:
      - Prod

jobs:
  deploy_to_github_pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    permissions:
      contents: write  # push to gh-pages
      pages: write     # deploy to GitHub Pages
      id-token: write  # authentication with GitHub Pages

    steps:
      # 1. Download the artifact from the triggering workflow
      - name: Download dist/ artifact
        uses: actions/download-artifact@v4
        with:
          name: vite-dist
          path: ./dist
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}

      # 2. Verify artifact contents
      - name: Verify artifact contents
        run: |
          echo "Downloaded artifact contents:"
          ls -la ./dist

      # 3. Zip downloaded artifact (optional if you really need it)
      - name: Zip downloaded artifact
        run: |
          zip -r dist.zip dist

      # 4. Add custom CNAME for GitHub Pages
      - name: Set up CNAME for GitHub Pages
        run: |
          echo "www.pavanclouds.com" > ./dist/CNAME

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages with custom domain
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
