name: GitHub Pages Deployment Workflow
on:
    workflow_run:
        workflows: ["SAST and CI/CD Pipeline for Personal Portfolio 3D"]
        types:
            - completed

jobs:
  # Deploy the application to github pages using gh-pages and custom domain
  deploy_to_github_pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    permissions:
      contents: write # Required to push to the gh-pages branch
      pages: write # Required to deploy to GitHub Pages
      id-token: write # Required for authentication with GitHub Pages

    steps:
      # Download the dist/ artifact from the previous job
      - name: Download dist/ artifact
        uses: actions/download-artifact@v4
        with:
          name: vite-dist
          path: ./dist

      - name: Verify artifact contents
        run: |
          ls -la

      - name: Zip downloaded artifact
        run: |
          zip -r dist.zip dist

      - name: Set up CNAME for GitHub Pages
        run: |
          echo "www.pavanclouds.com" > ./dist/CNAME

      - name: Deploy to GitHub Pages with custom domain
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # publish_branch: gh-pages
          